In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#import data

In [4]:
ipl_ball=pd.read_csv(f"E:\Datasets\IPL Ball-by-Ball 2008-2020.csv\IPL Ball-by-Ball 2008-2020 1.csv")

In [5]:
ipl_bat=pd.read_csv(f"E:\Datasets\IPL Ball-by-Ball 2008-2020.csv\IPL Matches 2008-2020.csv")

In [6]:
#lets chaking info for dataset

In [7]:
ipl_ball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193468 entries, 0 to 193467
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                193468 non-null  int64
 1   inning            193468 non-null  int64
 2   over              193468 non-null  int64
 3   ball              193468 non-null  int64
 4   batsman           193468 non-null  object
 5   non_striker       193468 non-null  object
 6   bowler            193468 non-null  object
 7   batsman_runs      193468 non-null  int64
 8   extra_runs        193468 non-null  int64
 9   total_runs        193468 non-null  int64
 10  non_boundary      193468 non-null  int64
 11  is_wicket         193468 non-null  int64
 12  dismissal_kind    9495 non-null    object
 13  player_dismissed  9495 non-null    object
 14  fielder           6784 non-null    object
 15  extras_type       10233 non-null   object
 16  batting_team      193468 non-null  object
 17  bowling_team      193277 non-null  object
dtypes: int64(9), object(9)
memory usage: 26.6+ MB

In [8]:
ipl_bat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [9]:
ipl_ball.head(60)

,id,inning,over,ball,batsman,non_striker,bowler,batsman_runs,extra_runs,total_runs,non_boundary,is_wicket,dismissal_kind,player_dismissed,fielder,extras_type,batting_team,bowling_team
0,335982,1,6,5,RT Ponting,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
1,335982,1,6,6,BB McCullum,RT Ponting,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
2,335982,1,7,1,BB McCullum,RT Ponting,Z Khan,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
3,335982,1,7,2,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
4,335982,1,7,3,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
5,335982,1,7,4,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
6,335982,1,7,5,RT Ponting,BB McCullum,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
7,335982,1,7,6,BB McCullum,RT Ponting,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
8,335982,1,8,1,BB McCullum,RT Ponting,JH Kallis,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
9,335982,1,8,2,BB McCullum,RT Ponting,JH Kallis,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
10,335982,1,8,3,BB McCullum,RT Ponting,JH Kallis,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
11,335982,1,8,4,BB McCullum,RT Ponting,JH Kallis,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
12,335982,1,8,5,RT Ponting,BB McCullum,JH Kallis,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
13,335982,1,8,6,BB McCullum,RT Ponting,JH Kallis,2,0,2,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
14,335982,1,9,1,RT Ponting,BB McCullum,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
15,335982,1,9,2,BB McCullum,RT Ponting,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
16,335982,1,9,3,RT Ponting,BB McCullum,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
17,335982,1,9,4,BB McCullum,RT Ponting,SB Joshi,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
18,335982,1,9,5,BB McCullum,RT Ponting,SB Joshi,6,0,6,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
19,335982,1,9,6,BB McCullum,RT Ponting,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
20,335982,1,10,1,BB McCullum,RT Ponting,JH Kallis,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
21,335982,1,10,2,RT Ponting,BB McCullum,JH Kallis,4,0,4,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
22,335982,1,10,3,RT Ponting,BB McCullum,JH Kallis,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
23,335982,1,10,4,RT Ponting,BB McCullum,JH Kallis,6,0,6,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
24,335982,1,10,5,RT Ponting,BB McCullum,JH Kallis,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
25,335982,1,10,6,RT Ponting,BB McCullum,JH Kallis,0,4,4,0,0,NaN,NaN,NaN,byes,Kolkata Knight Riders,Royal Challengers Bangalore
26,335982,1,11,1,BB McCullum,RT Ponting,SB Joshi,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
27,335982,1,11,2,BB McCullum,RT Ponting,SB Joshi,6,0,6,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
28,335982,1,11,3,BB McCullum,RT Ponting,SB Joshi,2,0,2,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
29,335982,1,11,4,BB McCullum,RT Ponting,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
30,335982,1,11,5,RT Ponting,BB McCullum,SB Joshi,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
31,335982,1,11,6,RT Ponting,BB McCullum,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
32,335982,1,12,1,RT Ponting,BB McCullum,JH Kallis,0,0,0,0,1,caught,RT Ponting,P Kumar,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
33,335982,1,12,2,BB McCullum,DJ Hussey,JH Kallis,4,0,4,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
34,335982,1,12,3,BB McCullum,DJ Hussey,JH Kallis,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
35,335982,1,12,4,BB McCullum,DJ Hussey,JH Kallis,2,0,2,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
36,335982,1,12,5,BB McCullum,DJ Hussey,JH Kallis,0,1,1,0,0,NaN,NaN,NaN,wides,Kolkata Knight Riders,Royal Challengers Bangalore
37,335982,1,12,6,BB McCullum,DJ Hussey,JH Kallis,4,0,4,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
38,335982,1,12,7,BB McCullum,DJ Hussey,JH Kallis,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
39,335982,1,13,1,BB McCullum,DJ Hussey,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
40,335982,1,13,2,DJ Hussey,BB McCullum,SB Joshi,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
41,335982,1,13,3,DJ Hussey,BB McCullum,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
42,335982,1,13,4,BB McCullum,DJ Hussey,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
43,335982,1,13,5,DJ Hussey,BB McCullum,SB Joshi,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
44,335982,1,13,6,BB McCullum,DJ Hussey,SB Joshi,2,0,2,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
45,335982,1,14,1,DJ Hussey,BB McCullum,CL White,4,0,4,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
46,335982,1,14,2,DJ Hussey,BB McCullum,CL White,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
47,335982,1,14,3,BB McCullum,DJ Hussey,CL White,6,0,6,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
48,335982,1,14,4,BB McCullum,DJ Hussey,CL White,4,0,4,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
49,335982,1,14,5,BB McCullum,DJ Hussey,CL White,0,2,2,0,0,NaN,NaN,NaN,wides,Kolkata Knight Riders,Royal Challengers Bangalore
50,335982,1,14,6,DJ Hussey,BB McCullum,CL White,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
51,335982,1,14,7,BB McCullum,DJ Hussey,CL White,6,0,6,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
52,335982,1,15,1,DJ Hussey,BB McCullum,AA Noffke,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
53,335982,1,15,2,DJ Hussey,BB McCullum,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
54,335982,1,15,3,BB McCullum,DJ Hussey,AA Noffke,2,0,2,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
55,335982,1,15,4,BB McCullum,DJ Hussey,AA Noffke,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
56,335982,1,15,5,BB McCullum,DJ Hussey,AA Noffke,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
57,335982,1,15,6,DJ Hussey,BB McCullum,AA Noffke,0,0,0,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
58,335982,1,16,1,BB McCullum,DJ Hussey,Z Khan,1,0,1,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore
59,335982,1,16,2,DJ Hussey,BB McCullum,Z Khan,2,0,2,0,0,NaN,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore

In [10]:
ipl_bat.head(5)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [11]:
ipl_ball=ipl_ball.fillna(0)
ipl_bat=ipl_bat.fillna(0)

In [12]:
ipl_ball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193468 entries, 0 to 193467
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                193468 non-null  int64
 1   inning            193468 non-null  int64
 2   over              193468 non-null  int64
 3   ball              193468 non-null  int64
 4   batsman           193468 non-null  object
 5   non_striker       193468 non-null  object
 6   bowler            193468 non-null  object
 7   batsman_runs      193468 non-null  int64
 8   extra_runs        193468 non-null  int64
 9   total_runs        193468 non-null  int64
 10  non_boundary      193468 non-null  int64
 11  is_wicket         193468 non-null  int64
 12  dismissal_kind    193468 non-null  object
 13  player_dismissed  193468 non-null  object
 14  fielder           193468 non-null  object
 15  extras_type       193468 non-null  object
 16  batting_team      193468 non-null  object
 17  bowling_team      193468 non-null  object
dtypes: int64(9), object(9)
memory usage: 26.6+ MB

In [13]:
ipl_bat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             816 non-null    object
 2   date             816 non-null    object
 3   player_of_match  816 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           816 non-null    object
 11  result           816 non-null    object
 12  result_margin    816 non-null    float64
 13  eliminator       816 non-null    object
 14  method           816 non-null    object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [14]:
ipl_ball.duplicated().sum()

1

# How many runs were scored in each season?   What were the runs scored per match in different seasons?

In [ ]:
un_id=ipl_ball.id.unique()

for i in un_id:
    print(f"{i} :",ipl_ball.groupby("id").get_group(i).count().id ,":",
        ipl_ball.groupby("id").get_group(i).total_runs.sum())

335982 : 225 : 304
335983 : 248 : 447
335984 : 219 : 261
335985 : 246 : 331
335986 : 240 : 222
335987 : 241 : 334
335988 : 205 : 285
335989 : 255 : 410
335990 : 248 : 431
335991 : 250 : 298
335992 : 229 : 273
335993 : 233 : 299
335994 : 202 : 309
335995 : 248 : 320
335996 : 247 : 343
335997 : 243 : 275
335998 : 243 : 372
335999 : 239 : 331
336000 : 249 : 347
336001 : 244 : 341
336002 : 240 : 336
336003 : 247 : 347
336004 : 238 : 295
336005 : 209 : 219
336006 : 238 : 253
336007 : 236 : 292
336008 : 202 : 207
336009 : 251 : 375
336010 : 197 : 253
336011 : 223 : 281
336012 : 217 : 248
336013 : 253 : 344
336014 : 252 : 385
336015 : 245 : 315
336016 : 221 : 287
336017 : 238 : 243
336018 : 221 : 314
336019 : 245 : 401
336020 : 247 : 376
336021 : 136 : 135
336022 : 123 : 212
336023 : 252 : 329
336024 : 252 : 331
336025 : 175 : 204
336026 : 236 : 312
336027 : 224 : 297
336028 : 249 : 377
336029 : 247 : 238
336031 : 243 : 353
336032 : 247 : 355
336033 : 248 : 412
336034 : 244 : 309
336035 : 248 : 349
336036 : 253 : 291
336037 : 250 : 295
336038 : 223 : 279
336039 : 215 : 228
336040 : 250 : 327
392181 : 244 : 311
392182 : 221 : 191
392183 : 108 : 162
392184 : 199 : 205
392185 : 220 : 266
392186 : 187 : 237
392188 : 247 : 344
392189 : 246 : 369
392190 : 256 : 300
392191 : 242 : 341
392192 : 252 : 324
392194 : 246 : 299
392195 : 253 : 251
392196 : 248 : 334
392197 : 219 : 282
392198 : 240 : 290
392199 : 248 : 282
392200 : 254 : 235
392201 : 243 : 298
392202 : 243 : 290
392203 : 253 : 287
392204 : 247 : 282
392205 : 246 : 283
392206 : 246 : 308
392207 : 249 : 307
392208 : 238 : 299
392209 : 215 : 278
392210 : 252 : 344
392211 : 240 : 311
392212 : 245 : 271
392213 : 218 : 212
392214 : 220 : 359
392215 : 247 : 234
392216 : 247 : 337
392217 : 238 : 281
392218 : 255 : 298
392219 : 234 : 248
392220 : 241 : 279
392221 : 248 : 349
392222 : 234 : 241
392223 : 249 : 334
392224 : 240 : 261
392225 : 251 : 288
392226 : 249 : 243
392227 : 242 : 298
392228 : 248 : 326
392229 : 250 : 267
392230 : 251 : 286
392231 : 250 : 377
392232 : 239 : 269
392233 : 242 : 203
392234 : 245 : 208
392235 : 241 : 331
392236 : 247 : 328
392237 : 237 : 307
392238 : 238 : 295
392239 : 247 : 280
419106 : 254 : 311
419107 : 254 : 420
419108 : 246 : 288
419109 : 243 : 271
419110 : 254 : 349
419111 : 232 : 283
419112 : 248 : 407
419113 : 240 : 273
419114 : 230 : 338
419115 : 195 : 185
419116 : 248 : 375
419117 : 243 : 334
419118 : 244 : 302
419119 : 239 : 306
419120 : 242 : 332
419121 : 250 : 272
419122 : 241 : 311
419123 : 250 : 306
419124 : 246 : 335
419125 : 250 : 361
419126 : 224 : 299
419127 : 255 : 327
419128 : 252 : 349
419129 : 245 : 337
419130 : 239 : 303
419131 : 250 : 314
419132 : 251 : 327
419133 : 241 : 323
419134 : 233 : 309
419135 : 251 : 338
419136 : 242 : 365
419137 : 247 : 469
419138 : 238 : 293
419139 : 239 : 404
419140 : 244 : 331
419141 : 249 : 316
419142 : 257 : 306
419143 : 223 : 310
419144 : 250 : 348
419145 : 251 : 370
419146 : 240 : 312
419147 : 244 : 277
419148 : 232 : 322
419149 : 239 : 223
419150 : 251 : 311
419151 : 249 : 289
419152 : 247 : 327
419153 : 212 : 282
419154 : 217 : 262
419155 : 242 : 225
419156 : 247 : 352
419157 : 248 : 325
419158 : 225 : 265
419159 : 246 : 387
419160 : 244 : 279
419161 : 233 : 268
419162 : 255 : 333
419163 : 241 : 246
419164 : 198 : 168
419165 : 249 : 314
501198 : 244 : 304
501199 : 237 : 278
501200 : 245 : 323
501201 : 218 : 194
501202 : 207 : 225
501203 : 247 : 317
501204 : 238 : 303
501205 : 237 : 283
501206 : 238 : 381
501207 : 246 : 299
501208 : 250 : 317
501209 : 242 : 319
501210 : 247 : 366
501211 : 246 : 345
501212 : 235 : 331
501213 : 247 : 377
501214 : 185 : 166
501215 : 196 : 266
501216 : 244 : 320
501218 : 230 : 242
501219 : 245 : 258
501220 : 249 : 342
501221 : 257 : 320
501222 : 242 : 346
501223 : 249 : 433
501224 : 245 : 307
501225 : 209 : 220
501226 : 246 : 259
501227 : 251 : 321
501228 : 247 : 286
501229 : 228 : 203
501230 : 250 : 279
501231 : 234 : 189
501232 : 246 : 336
501233 : 239 : 276
501234 : 233 : 239
501235 : 241 : 287
501236 : 247 : 311
501237 : 242 : 295
501238 : 226 : 281
501239 : 249 : 318
501240 : 238 : 296
501241 : 248 : 299
501242 : 247 : 295
501243 : 247 : 354
501244 : 246 : 325
501245 : 186 : 175
501246 : 250 : 324
501247 : 211 : 253
501248 : 229 : 239
501249 : 246 : 329
501250 : 234 : 273
501251 : 204 : 250
501252 : 229 : 297
501253 : 246 : 334
501254 : 247 : 359
501255 : 159 : 194
501256 : 249 : 260
501257 : 251 : 311
501258 : 161 : 195
501259 : 243 : 274
501260 : 232 : 353
501261 : 249 : 293
501262 : 227 : 237
501263 : 203 : 267
501264 : 239 : 314
501265 : 63 : 56
501266 : 242 : 257
501267 : 248 : 353
501268 : 249 : 352
501269 : 241 : 295
501270 : 251 : 327
501271 : 244 : 352
548306 : 230 : 227
548307 : 142 : 197
548308 : 247 : 230
548309 : 249 : 351
548310 : 244 : 294
548311 : 233 : 312
548312 : 248 : 306
548313 : 248 : 310
548314 : 243 : 280
548315 : 249 : 288
548316 : 204 : 221
548317 : 241 : 367
548318 : 254 : 413
548319 : 225 : 231
548320 : 246 : 268
548321 : 245 : 319
548322 : 243 : 311
548323 : 243 : 266
548324 : 241 : 331
548325 : 215 : 185
548326 : 249 : 393
548327 : 247 : 368
548328 : 222 : 251
548329 : 225 : 380
548330 : 245 : 315
548331 : 248 : 329
548332 : 244 : 293
548333 : 252 : 364
548334 : 246 : 327
548335 : 242 : 253
548336 : 249 : 332
548337 : 218 : 294
548339 : 249 : 339
548341 : 248 : 336
548342 : 249 : 377
548343 : 248 : 305
548344 : 247 : 333
548345 : 247 : 303
548346 : 232 : 201
548347 : 250 : 279
548348 : 246 : 359
548349 : 216 : 285
548350 : 244 : 321
548351 : 249 : 239
548352 : 245 : 310
548353 : 255 : 293
548354 : 251 : 311
548355 : 248 : 347
548356 : 240 : 366
548357 : 242 : 307
548358 : 221 : 251
548359 : 246 : 315
548360 : 233 : 283
548361 : 243 : 253
548362 : 246 : 311
548363 : 245 : 337
548364 : 218 : 229
548365 : 244 : 295
548366 : 245 : 384
548367 : 256 : 344
548368 : 242 : 318
548369 : 236 : 276
548370 : 245 : 248
548371 : 222 : 243
548372 : 248 : 409
548373 : 243 : 254
548374 : 236 : 286
548375 : 246 : 238
548376 : 247 : 255
548377 : 250 : 325
548378 : 246 : 306
548379 : 249 : 336
548380 : 229 : 358
548381 : 248 : 382
597998 : 239 : 257
597999 : 247 : 310
598000 : 237 : 230
598001 : 248 : 325
598002 : 252 : 287
598003 : 198 : 199
598004 : 248 : 260
598005 : 242 : 269
598006 : 248 : 374
598007 : 227 : 277
598008 : 237 : 312
598009 : 239 : 293
598010 : 243 : 229
598011 : 247 : 325
598012 : 253 : 331
598013 : 247 : 312
598014 : 235 : 250
598015 : 244 : 294
598016 : 248 : 310
598017 : 246 : 304
598018 : 239 : 227
598019 : 241 : 271
598020 : 234 : 252
598021 : 236 : 250
598022 : 237 : 243
598023 : 232 : 240
598024 : 228 : 326
598025 : 244 : 371
598026 : 248 : 371
598027 : 251 : 396
598028 : 244 : 335
598029 : 241 : 321
598030 : 246 : 319
598031 : 233 : 299
598032 : 237 : 290
598033 : 247 : 330
598034 : 249 : 386
598035 : 251 : 313
598036 : 246 : 344
598037 : 251 : 344
598038 : 245 : 291
598039 : 236 : 259
598040 : 233 : 273
598041 : 242 : 357
598042 : 247 : 357
598043 : 234 : 265
598044 : 203 : 161
598045 : 239 : 350
598046 : 220 : 218
598047 : 249 : 360
598048 : 235 : 323
598049 : 237 : 309
598050 : 236 : 275
598051 : 252 : 369
598052 : 240 : 292
598053 : 244 : 258
598054 : 249 : 362
598055 : 237 : 228
598056 : 243 : 270
598057 : 241 : 231
598058 : 227 : 285
598059 : 226 : 241
598060 : 248 : 362
598061 : 244 : 333
598062 : 248 : 303
598063 : 248 : 318

# Who has umpired the most?

In [ ]:
# un_ump=ipl_bat.umpire1.unique()
# maxi=0
# ump=""
# for i in un_ump:
#     x=ipl_bat.groupby("umpire1").get_group(i).count().id
#     #print(f"{i}:",x)
#     if x>maxi:
#         maxi=x
#         ump=i    
# print(ump,":",maxi)
ipl_bat.umpire1.value_counts().head(3)

In [ ]:
# # Which team has won the most tosses? What does the team decide after winning the toss?
# team =ipl_bat.toss_winner.unique()
# max=0
# winner=""
# for i in team :
#     matches=ipl_bat.groupby("toss_winner").get_group(i).count().id
#     if matches>max:
#         max=matches
#         winner=i
# print(winner,":",max)
ipl_bat.winner.value_counts().head(3)

In [ ]:
#decision taken by toss_winning teams 
plt.hist(ipl_bat.toss_decision);

In [ ]:
#decision taken by most toss winning team
plt.hist(ipl_bat.groupby("toss_winner").get_group("Mumbai Indians").toss_decision)

In [ ]:
plt.bar(ipl_bat.player_of_match.value_counts()[0:5].keys(),ipl_bat.player_of_match.value_counts()[0:5])

In [ ]:
# team =ipl_bat.toss_winner.unique()
# toss_w=[]
# match_w=[]
# for i in team :
#     x=ipl_bat.groupby("toss_winner").get_group(i).count().id
#     y=ipl_bat.groupby("winner").get_group(i).count().id
#     print(f"{i}",x, ";",y)
#     toss_w.append(x)
#     match_w.append(y)
plt.figure(figsize=(20,5))
plt.bar(ipl_bat.winner.value_counts()[0:10].keys(),ipl_bat.winner.value_counts()[0:10])
plt.bar(ipl_bat.toss_winner.value_counts()[0:10].keys(),ipl_bat.toss_winner.value_counts()[0:10],width= 0.25)
plt.xticks(rotation = 25);
plt.xlabel('Name of top 10 team')
plt.ylabel('Number of winning')
plt.legend(["match winner",'toss_winner'], loc ="upper right")
plt.title('top 10 team winning & toss winning')

In [ ]:
# plt.figure(figsize=(20,5))
# plt.plot(team,toss_w)
# plt.plot(team,match_w)
# plt.xlabel("Name of team", fontdict = {'family':'serif','color':'blue','size':20})
# plt.ylabel("Number of winning toss/match", fontdict = {'family':'serif','color':'blue','size':20})
# plt.legend(["toss",'match'], loc ="upper right")
# plt.xticks(rotation = 25);

In [ ]:
#By seeing this graph we can says thaa if we win the toss then we have a large probablity to win the match

In [ ]:
count=0
loss=0
total=ipl_bat.id.nunique()
for i in range(total):
    if ipl_bat.toss_winner[i]==ipl_bat.winner[i]:
        count+=1
    else:
        loss+=1
print("number of match winner who also win the toss:",count)
print("number of match winner who loss the toss:",loss)

# print(ipl_bat.winner.value_counts())
# print(ipl_bat.toss_winner.value_counts())

In [ ]:
#by seeing this we can not says that if you win the toss means you win the match

In [ ]:
#How many times chasing team has won the match?
count1=0
loss=0
x=0
y=0
total=ipl_bat.id.nunique()
for i in range(total):
    
    if ipl_bat.toss_decision[i]=="field":
        if ipl_bat.toss_winner[i]==ipl_bat.winner[i]:
            count1+=1
        else:
            loss+=1
    else :
        if ipl_bat.toss_winner[i]==ipl_bat.winner[i]:
            x+=1
        else:
            y+=1
print("Number of team which chasing and  win both toss and match:",count1)
print("Number of team which chasing and  loss toss but win match:",loss)
print("Number of team which chose bating and win both toss and match:",x)
print("Number of team which chose bating and loss toss but win match:",y)

In [ ]:
plt.figure(figsize=(7,7))
li=[count1,loss,x,y]
myexplode = [0.01,0.01,0.01,0.01]
plt.pie(li, labels=[f"chasing and win both match and toss {count1}",
                    f"chasing and win match but loss toss {loss}",
                    f"batting and win both match and toss {x}",
                    f"batting and win match but loss toss {y}"],
                   explode = myexplode,shadow=True);

In [ ]:
# team =ipl_bat.winner.unique()
# max=0
# winner=""
# for i in team :
#     matches=ipl_bat.groupby("winner").get_group(i).count().id
#     if matches>max:
#         max=matches
#         winner=i
# print(winner,":",max)
ipl_bat.winner.value_counts().head(1)

###### mumbai indians win the most matches .

In [ ]:
#Which all teams had won this tournament?
ipl_bat.winner.unique()

In [ ]:
#Which team has played the most number of matches?
team =ipl_bat.team1.unique()
max=0
t_name=""
for i in team:
    t1=ipl_bat.groupby("team1").get_group(i).count().id
    t2=ipl_bat.groupby("team2").get_group(i).count().id
    T=t1+t2
    print (f"{i}:",T)
    if T>max:
        max=T
        t_name=i
print(f"\nTeam has played the most number of matches is {t_name} ",max)
ipl_bat.team1

In [ ]:
#Which team has the highest winning percentage?
team =ipl_bat.team1.unique()
t_name=""
for i in team:
    w=ipl_bat.groupby("winner").get_group(i).count().id
    t1=ipl_bat.groupby("team1").get_group(i).count().id
    t2=ipl_bat.groupby("team2").get_group(i).count().id
    T=t1+t2
    print(f"percentage of winning of {i}: ",(100*w)/T)

In [ ]:
#Is there any lucky venue for a particular team?
team =ipl_bat.team1.unique()
venue=ipl_bat.venue.unique()
#for i in team:
 #   count=0
max=0
tname="Royal Challengers Bangalore"
   # print("\nname of team :",i)
for j in venue:
    count=0
   
    for k in range(ipl_bat.venue.count()):
        if ipl_bat.venue[k]== j and ipl_bat.winner[k]==tname:
            count+=1
    if count>max:
        max=count
  #  print(f"{j}:",count)
print(f"lucky stadium for {tname} is:",max)

In [ ]:
ipl_ball.head()

In [ ]:
team.batsman_runs.value_counts()

In [ ]:
team .batsman_runs.value_counts()

In [ ]:
team_df=pd.DataFrame();
for i in ipl_ball.id.unique():
    team=ipl_ball[ipl_ball["id"]==i]
    
    for j in team.batting_team.unique():
        team1=team[team["batting_team"].str.contains(f"{j}")];
        team_df= team_df.append({"id":i,
                             "batting_team":team1.batting_team.unique(),
                             "batsman_runs":team1.batsman_runs.sum(),
                             "extra_runs":team1.extra_runs.sum(),
                             "total_runs":team1.total_runs.sum()},ignore_index=True);

In [ ]:
team_df

In [ ]:
 team_df.total_runs.max()